spring:
  profiles:
    active: local
  application:
    name: supper-stock


server:
  port: 8082
  tomcat:
    max-threads: 2000
    max-connections: 2000


#  context-path: /
---
spring:
  profiles: local
  aop:
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  quartz:
    properties:
      org:
        quartz:
          scheduler:
    job-store-type: memory

  freemarker:
    cache: false
    request-context-attribute: req  #req访问request
    suffix: .tpl  #后缀名
    content-type: text/html
    enabled: true
    template-loader-path: classpath:/templates #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点



  datasource:
    url: jdbc:mysql://172.16.32.243:3306/db_supper_stock?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  #  url: jdbc:mysql://localhost:3306/db_pre_k8s_op?useSSL=false&useUnicode=true&characterEncoding=utf8
  #  username: root
  #  password: Pass@123
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 1
    maxActive: 1
    minIdle: 1
    validationQuery: SELECT 1


datasource:
  url: jdbc:mysql://172.16.32.243:3306/db_supper_stock?useSSL=false&useUnicode=true&characterEncoding=utf8
  username: root
  password: root
#  url: jdbc:mysql://localhost:3306/db_pre_k8s_op?useSSL=false&useUnicode=true&characterEncoding=utf8
#  username: root
#  password: Pass@123
  driverClassName: com.mysql.jdbc.Driver
  initialSize: 10
  maxActive: 30
  minIdle: 5
  validationQuery: SELECT 1

mybatis:
  mapper-locations: classpath:com.pers.yefei.supper.stock.model.gen.mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.pers.yefei.supper.stock.model.gen.pojo # 注意：对应实体类的路径
  config-location: classpath:mybatis-config.xml


http:
  maxTotal: 100                       #最大连接数
  defaultMaxPerRoute: 20              #并发数
  connectTimeout: 1000                #创建连接的最长时间
  connectionRequestTimeout: 500       #从连接池中获取到连接的最长时间
  socketTimeout: 10000                #数据传输的最长时间
  staleConnectionCheckEnabled: true   #提交请求前测试连接是否可用


logging:
  config: classpath:logback-local.xml


---
spring:
  profiles: pre
  aop:
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  quartz:
    properties:
      org:
        quartz:
          scheduler:
    job-store-type: memory

  freemarker:
    cache: false
    request-context-attribute: req  #req访问request
    suffix: .tpl  #后缀名
    content-type: text/html
    enabled: true
    template-loader-path: classpath:/templates #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点



  datasource:
    url: jdbc:mysql://172.16.32.243:3306/db_supper_stock?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  #  url: jdbc:mysql://localhost:3306/db_pre_k8s_op?useSSL=false&useUnicode=true&characterEncoding=utf8
  #  username: root
  #  password: Pass@123
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 1
    maxActive: 1
    minIdle: 1
    validationQuery: SELECT 1


datasource:
  url: jdbc:mysql://172.16.32.243:3306/db_supper_stock?useSSL=false&useUnicode=true&characterEncoding=utf8
  username: root
  password: root
#  url: jdbc:mysql://localhost:3306/db_pre_k8s_op?useSSL=false&useUnicode=true&characterEncoding=utf8
#  username: root
#  password: Pass@123
  driverClassName: com.mysql.jdbc.Driver
  initialSize: 10
  maxActive: 30
  minIdle: 5
  validationQuery: SELECT 1

mybatis:
  mapper-locations: classpath:com.pers.yefei.supper.stock.model.gen.mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.pers.yefei.supper.stock.model.gen.pojo # 注意：对应实体类的路径
  config-location: classpath:mybatis-config.xml


http:
  maxTotal: 100                       #最大连接数
  defaultMaxPerRoute: 20              #并发数
  connectTimeout: 1000                #创建连接的最长时间
  connectionRequestTimeout: 500       #从连接池中获取到连接的最长时间
  socketTimeout: 10000                #数据传输的最长时间
  staleConnectionCheckEnabled: true   #提交请求前测试连接是否可用


logging:
  config: classpath:logback-pre.xml


