
spring:
  profiles: prod
  aop:
    auto: true
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  quartz:
    properties:
      org:
        quartz:
          scheduler:
    job-store-type: memory

  freemarker:
    cache: false
    request-context-attribute: req  #req访问request
    suffix: .tpl  #后缀名
    content-type: text/html
    enabled: true
    template-loader-path: classpath:/templates #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点


datasource:
  url: jdbc:mysql://localhost:3306/db_supper_stock?useSSL=false&useUnicode=true&characterEncoding=utf8
  username: dev
  password: Pass@123
#  url: jdbc:mysql://localhost:3306/db_pre_k8s_op?useSSL=false&useUnicode=true&characterEncoding=utf8
#  username: root
#  password: Pass@123
  driverClassName: com.mysql.jdbc.Driver
  initialSize: 2
  maxActive: 3
  minIdle: 2
  validationQuery: SELECT 1

mybatis:
  mapper-locations: classpath:com.pers.yefei.supper.stock.model.gen.mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.pers.yefei.supper.stock.model.gen.pojo # 注意：对应实体类的路径
  config-location: classpath:mybatis-config.xml


http:
  maxTotal: 100                       #最大连接数
  defaultMaxPerRoute: 20              #并发数
  connectTimeout: 1000                #创建连接的最长时间
  connectionRequestTimeout: 500       #从连接池中获取到连接的最长时间
  socketTimeout: 10000                #数据传输的最长时间
  staleConnectionCheckEnabled: true   #提交请求前测试连接是否可用


logging:
  config: classpath:logback-pre.xml


